### PR TITLE
OO.extend() and OO.inherit() support static properties.

### PR DESCRIPTION
**Pull request by obuchtala**
- either defined using OO.makeExtensible(clazz, staticProperties)
- or via proto.static = {...}

Look at test (oo.test.js) for usage.

### CODE REVIEW

**Comment by obuchtala** [comment]
@michael review plz

**Comment by obuchtala** [comment]
Note that proto.static is built-in, as it is an object merged into static as opposed to a single property copied over.

**Comment by michael** [comment]
So

``` js
Foo.extend({
  static: {name: 'bla'}
});
```

now works on any Substance.OO object by default..?

**Comment by obuchtala** [comment]
Yes. Good or bad?

**Comment by michael** [comment]
:+1:

**Comment by michael** [comment]
trying to apply it on my branch...

**Pull request merged**
