### PR TITLE
Refactor of triggerDidMount.

### PR DESCRIPTION
**Pull request by michael**
- Improved Component.mount
- Removed Component.prototype.mount

### CODE REVIEW

**Comment by michael** [comment]
Addresses #27 and #32. Please review and merge if happy. Additional component tests to follow in the next days.

**Comment by obuchtala** [comment]
:+1:

**Comment by michael** [comment]
I will add more tests and do some integration testing tomorrow before merging.

**Comment by obuchtala** [comment]
Cool

**Pull request merged**
