### PR TITLE
Polish

### PR DESCRIPTION
**Pull request by michael**

### CODE REVIEW

**Comment by obuchtala** [comment]
@michael I saw that u use the mixin pattern in a way I did not consider.

```
DocumentedNode.extend(ClassNode, MemberContainerMixin)
```

is that actually working?

**Comment by michael** [comment]
Seems to be... What's the correct usage?

**Comment by obuchtala** [comment]
Not that it is wrong... Just didn't think of the case of having a mixin + the Prototype.
But when it's working it is probably fine :)

Edit: i.e. Prototype implicitly taken.

**Comment by obuchtala** [comment]
The explicit way would be

```
DocumentedNode.extend(ClassNode, MemberContainerMixin, ClassNode.Prototype)
```

**Comment by obuchtala** [comment]
But no need to change this, if you find this to be working.

**Comment by obuchtala** [comment]
Just that I need to document it and maybe add a test-case.

**Comment by michael** [comment]
Ok :) need to go now. But you can review and merge. I tested with notepad
example, not with lens yet.

**Comment by obuchtala** [comment]
Will do :)

**Comment by obuchtala** [comment]
reviewed :+1:

**Comment by obuchtala** [comment]
Will merge when :frog:

**Pull request merged**
