### PR TITLE
Collab: pass userId to backend when storing changes

### PR DESCRIPTION
**Pull request by Integral**

### CODE REVIEW

**Comment by michael** [comment]
This breaks the testsuite. You would need to update TestBackend also to make the test suite pass again.

**Comment by michael** [comment]
TestStore it's called. You could also rename to TestBackend and make changes in the CollabHub.test.js file.

**Comment by Integral** [comment]
@michael there are browserify or lodash issues...

```
[19:31:29] Starting 'test:karma'...
24 02 2016 19:31:29.879:WARN [plugin]: Error during loading "/Users/danielbeilinson/Projects/substance/node_modules/karma-browserify" plugin:
  Cannot find module 'lodash/collection/reduce'
24 02 2016 19:31:29.890:WARN [preprocess]: Can not load "browserify", it is not registered!
  Perhaps you are missing some plugin?
[19:31:29] 'test:karma' errored after 326 ms
[19:31:29] Error: No provider for "framework:browserify"! (Resolving: framework:browserify)
```

**Comment by michael** [comment]
Mhh karma depends on old lodash, but that should work fine when dependencies are resolved correctly. I triggered restart of the test run.. sometimes it has a hickup.

**Comment by Integral** [comment]
I also can't pass tests locally. Because of this.

**Comment by obuchtala** [comment]
I had this too yesterday, which resolved after wiping node_modules and npm installing again.
It was strange, as it took like two times. Seemed to be a node 4 problem or even an issue with using nvm.
So happy wiping ;)

**Comment by Integral** [comment]
Say it to travis-ci ;)

**Comment by obuchtala** [comment]
Travis might also just be choking... I restarted that one failing core.

**Comment by obuchtala** [comment]
But... hearing that both of u are not able to run tests locally makes me whine ;)

**Comment by obuchtala** [comment]
@michael  @Integral plz let me know when u have resolved the local testing issues.

**Comment by michael** [comment]
Tests were running fine for me locally.

**Comment by michael** [comment]
@Integral i need to finish a bunch of stuff, but will look at your PR's and merge them later today. Just one question: Are all the PR's independent or does one need the other to be applied first?

**Comment by obuchtala** [comment]
Ok then there is no prob.
Travis is choking sometimes. So whenever you see it failing out of nothing then just try restarting the build.

**Comment by Integral** [comment]
@michael, they are independent in repo context. But both has siblings in notepad repo.
@oliver---- Works good after wiping. Before wiping I saw that karma-browserify haven't got lodash inside its's node_modules folder (but have dependency in package.json). Strange npm...

**Pull request merged**
