### PR TITLE
WIP: KeyboardCommander

### PR DESCRIPTION
**Pull request by obuchtala**
was PR #666, now based on `develop`

### CODE REVIEW

**Comment by michael** [comment]
Can this be closed?

**Comment by obuchtala** [comment]
We have never merged this.
It has an interesting implementation of complex combos, contributed by @Integral 
I think it should go into a package, and we create an example showing how to use it.

**Comment by Integral** [comment]
There was an example a long long long time ago

**Comment by obuchtala** [comment]
Obsolete.

**Pull request closed without merging**
