### PR TITLE
Component refactor

### PR DESCRIPTION
**Pull request by obuchtala**
Rewrite of rendering implementation of Component.js
- $$ as parameter for render(): fixes issues with Substance used with two instances of the library code (~peerDependency)
- improved technical architecture
- better debuggability (via setting `RenderEngine.DEBUG = true`)
- automatically retain ancestors of ref'd components
- deep rerendering by default

### CODE REVIEW

**Comment by obuchtala** [comment]
Need to fix scrollTo

**Comment by obuchtala** [comment]
Also I did some profiling and it is clear that I need to to optimize some stuff in RenderingEngine.

**Comment by obuchtala** [comment]
Resolved performance problems. However there are some issues with retaining components in delicate nesting scenarios.

**Comment by obuchtala** [comment]
It
is
done

**Comment by obuchtala** [comment]
Still we should wait with merging this, as I have removed routing support, which was not satisfactory.
We have discussed a better approach which I want to try out on top of this branch.

**Comment by michael** [comment]
Nice! And yes, we should bring back the router and make it independent of the component state properties.

**Pull request merged**
