### PR TITLE
use serverUtils module for dev stuff

### PR DESCRIPTION
**Pull request by Integral**
for #327

### CODE REVIEW

**Comment by michael** [comment]
Looks good. I think this can go into the main substance repo though.

**Comment by Integral** [comment]
Hm... Where I should put it?

**Comment by michael** [comment]
util/server.js ?

**Comment by michael** [comment]
Could you make it so that sourcemaps are generated by default?

So that this:

``` js
app.use('/docs/app.css', serverUtils.bundleStyles(path.join(__dirname, 'doc', 'app.scss'), {file: 'app.css'}));
app.use('/docs/app.css.map', serverUtils.bundleStyles(path.join(__dirname, 'app', 'app.scss'), {file: 'app.css', map: true}));
```

becomes just one line?

**Comment by Integral** [comment]
If we are doing this in the same repo, than we could do it even in the one
line for js/css.

**Comment by Integral** [comment]
But once you want do it from external app, it is not possible. So this will not work say with lens.

**Comment by Integral** [comment]
So let's decide...

**Comment by michael** [comment]
Can you give examples? I'm not sure I follow for the two options we have.

**Comment by Integral** [comment]
@michael  there is no option if you want to use it in other applications
if you want to use one middleware for a few routes (app.css, and app.css.map), then you actually need express Router instance, but you can't send any parameters to this class. So you there is no way to tell what is the path to Router.

What we could try to do is to play with paths like '/docs/app.css*', so it will match both app.css and app.css.map, then we could use real middleware and pass any data there. But I'm not sure that it is possible...

**Comment by michael** [comment]
Still not sure I understand completely. Do you think something like that would work?

``` js
app.use('/docs', serverUtils.serveApp({
  js: path.join(__dirname, 'doc', 'app.js'),
  css: path.join(__dirname, 'doc', 'app.scss')
}));
```

If app.use does not work we can also do it like this:

``` js
serverUtils.serveApp(app, {
  js: path.join(__dirname, 'doc', 'app.js'),
  css: path.join(__dirname, 'doc', 'app.scss')
});
```

I really don't know the best practices in Express land. Regarding koa.. I would say not now. We use only so little things and Express is definitely familiar to more people.

**Comment by netsgnut** [comment]
I think use of `express.Router` to separate modules is currently one of the common practices found in the express ecosystem.

Chiming in for this another pattern, also commonly found:

``` js
app.use('/docs', serverUtils.serveBundle(function (bundle) {
  bundle.add('app.js', path.join(__dirname, 'doc', 'app.js'));
  bundle.add('app.css', path.join(__dirname, 'doc', 'app.css'), { map: true });
}));
```

What `serveBundle` does is just like what @michael's first sample code does, and returns an [express.Router](http://expressjs.com/en/guide/routing.html#express-router).

**Comment by Integral** [comment]
serverUtils.serveApp(app, {some data}) is good suggestion, will try

**Comment by Integral** [comment]
@michael check latest commit please

**Comment by michael** [comment]
Thanks a lot. Will review this tomorrow.

**Comment by michael** [comment]
I did some consolidation and added docs. I found out that you can serve the CSS source maps inline also, so we don't need two routes for it.

**Comment by Integral** [comment]
ok

**Pull request merged**
