### PR TITLE
Deal with empty containers.

### PR DESCRIPTION
**Pull request by michael**
Attempting to solve #50.

### CODE REVIEW

**Comment by michael** [comment]
Please review using substance/examples#master and commenting out all content in notepad/index.html

https://github.com/substance/examples/blob/master/notepad/index.html#L13-L17

I've seen some problems with selection mapping on empty containers. Maybe you can cover those cases. Let me know when I have your ok on this and I will do another style iteration and then merge.

**Comment by obuchtala** [comment]
Solved this by not attaching event handlers when container editor is empty.

**Comment by obuchtala** [comment]
Now you should be able to do the finishing.

**Comment by michael** [comment]
We have too many branches. I merge this into master and we can hot fix if there are problems.

**Pull request merged**
