### PR TITLE
Improved collabsession

### PR DESCRIPTION
**Pull request by michael**

### CODE REVIEW

**Comment by michael** [comment]
The CollabWriter example is working again. Only thing missing is the test suite. I don't know how to provide the same message queue dump. Messages look differently now because we changed the message format to an object notation.

**Comment by obuchtala** [comment]
Will do an iteration.

**Comment by michael** [comment]
I used a branch `collab-refactor` in the examples. Let me just check quickly if my yesterdays changes did not break anything for the examples.

**Comment by michael** [comment]
Looking good. Feel free to merge into `collab`.

**Comment by michael** [comment]
Ready for merge with master?

**Comment by obuchtala** [comment]
@michael I think u want to clean up first: https://github.com/substance/substance/blob/a28845db4ec2697f24a9ec43e0f13bfc78259c9b/collab/CollabSession.js#L49-L103

**Comment by obuchtala** [comment]
But then it is ready to get merged.

**Comment by michael** [comment]
Oh. True. Will do!

**Comment by michael** [comment]
Working on including snapshot API into CollabHub too. Maybe i can that in as well today. What's your opinion about the current file structure? Didn't have a better idea than moving collab-related features into a separate collab folder.

**Comment by obuchtala** [comment]
I think that's ok, as it is not in the way. We should add a dedicated README later.

**Comment by michael** [comment]
Sounds good. I will merge when green.

**Pull request merged**
