### PR TITLE
Dragmanager fix

### PR DESCRIPTION
**Pull request by obuchtala**
Removes setSelection() from initDrag (which causes problems).

### CODE REVIEW

**Comment by obuchtala** [comment]
@michael Just wondering how we could increase robustness of adding the dropzone layer. Are we sure that the dragzones are removed when something is going wrong? Does it work when user drags outside the editor?

**Comment by obuchtala** [comment]
Just checked. Seems fine to drag outside the editor.

**Comment by obuchtala** [comment]
Also checked: exceptions are no problems.

**Comment by michael** [comment]
Yeah I also found it surprisingly stable ;) Especially now we can drag between multiple scroll panes and surfaces.

**Comment by obuchtala** [comment]
Sweet :)

**Pull request merged**
