### PR TITLE
Implementing Component 'owners' correctly.

### PR DESCRIPTION
**Pull request by obuchtala**
Before, owners where the last Component instance entered during rendering,
and not the Component triggering the rendering.

### CODE REVIEW

**Comment by obuchtala** [comment]
@michael I pushed fixes to substance/demos#new-mount-api  and substance/lens#new-mount-api to make them work with this.

Edit: didn't change package.json, as I am using npm link ATM. Make sure you are testing with the right substance version.

**Comment by michael** [comment]
Looks like we miss to preserve elements in some cases. E.g. in lens#new-mount-api, when a citation is selected, the main section gets wiped and rerendered. Thus the scroll pos jumps to the beginning of the article.

**Comment by obuchtala** [comment]
I could extract the observed issue into a test case. This should be ok now.

**Comment by obuchtala** [comment]
Closing in favor of #346

**Pull request closed without merging**
