### PR TITLE
Custom tags

### PR DESCRIPTION
**Pull request by obuchtala**
- passing through custom tags
- detecting type description in custom tags

### CODE REVIEW

**Comment by obuchtala** [comment]
@michael 

I was thinking about how to document components.
Instead of introducing a constructor for the $$ API it seems more straight-forward to add '@props' and '@state' tags to the '@class' and render that with a special ComponentComponent.

**Comment by obuchtala** [comment]
merge when u r fine with it.

**Comment by obuchtala** [comment]
Merging.. we will continue in a new PR.

**Comment by michael** [comment]
Let me think... That approach sounds reasonable... just see the following problems:
- constructor would not show up as a member in the memberindex
- constructor as a class member is addressable through deep linking - we would not have that functionality for components then (bit unconsistent, also nice to be able to link to the constructor when there's a longer description for the class + examples.

What if we had the info stored as you describe but don't touch the ClassComponent at all but introduce a custom constructor component that checks if it's parent is a component by inspecting its tags? and then render either the $$ thing if it detects a component or delegate to the regular ConstructorComponent?

**Comment by obuchtala** [comment]
The problem is, there is no such constructor thing. Even hard to give it a consistent name.
What would you then show in the member index?

Edit: simply said, there is actually no constructor.

**Comment by michael** [comment]
No i mean.. we document the constructor as usual. In a separate comment block with @param tags and the class itself just gets the @component flag. Then we would have a constructor node also for components. and can show it in the member index?

**Comment by obuchtala** [comment]
How would you render it in member index?

**Comment by obuchtala** [comment]
From a technical point of view: Components have a private constructor and an external so called 'named constructor' which is a static function of Component. (which makes it more a factory method than a named ctor) 
Edit: not even a factory. Component.$$ just creates a ComponentElement. So there is actually no way to create a Component directly.

**Comment by michael** [comment]
Hmm true.. mah maybe we should not document them at all. Just via example?

**Comment by obuchtala** [comment]
I would prefer to have a nice dedicated section for props and states in a component's documentation.
Most often you don't document the rest of a component's API, just what it is and how to use it.
You could go for a manually crafted doc, though, reusing the type notation is convenient.

**Comment by michael** [comment]
Agreed. It's more like a usage section in the Component case.. not a constructor in a typical sense.

Something like this structure:

**TextPropertyEditor**
Component defined in ui/Component.js#...

The text property editor.

**Props:**
- path Array path to text property
- commands SurfaceCommand[] array of SurfaceCommand classes

**Example:**

``` js
$$(TextPropertyEditor, {
  name: 'authorNameEditor',
  path: ['author_1', 'name'],
  commands: [EmphasisCommand]
})
```

**Comment by obuchtala** [comment]
:+1:  And maybe even a states section (in other cases).

**Comment by michael** [comment]
That's how we do it! I will work on this in the evening. I think I have everything I need data-wise?

**Comment by obuchtala** [comment]
yup :)

**Pull request merged**
