### PR TITLE
Extend EventEmitter on top level, so we don't need mixins.

### PR DESCRIPTION
**Pull request by michael**

### CODE REVIEW

**Comment by michael** [comment]
Last commit breaks DOMElement.test.js.

```
not ok 746 .. and even the click handler should still work
  ---
    operator: equal
    expected: 1
    actual:   0
    at: Test.<anonymous> (/Users/michael/projects/substance/substance/test/ui/DOMElement.test.js:104:5)
```

@oliver---- How can I run the tests in the browser for debugging? Couldn't get this to work.

**Comment by obuchtala** [comment]
Making DOMElement an EventEmitter is not correct, as DOMElement immitates the DOM event API.
1. We should find out why EventEmitter.mixin is not working as expected
2. Making ContainerAnnotationAnchor an EventEmitter is fine

**Comment by obuchtala** [comment]
if you run `node make -s build test` the test-suite should be served

**Comment by michael** [comment]
The problem is not the EventEmitter.mixin call. It's the EventEmitter.call(this) in the constructor.

> Class constructor EventEmitter cannot be invoked without 'new'.

**Comment by obuchtala** [comment]
You don't need to call EventEmitter ctor anymore. It is a pure mixin now.

**Comment by michael** [comment]
Ah ok.. then i just remove those calls. Thanks!

**Comment by michael** [comment]
Ad running browser tests: I ran `node make -s build test` with a fresh install but get the error that test is not present. There's some invalid JS syntax there.

image

**Comment by michael** [comment]
Ready to merge if green.

**Comment by michael** [comment]
need to run for lunch.

**Comment by obuchtala** [comment]
Rebasing this.

**Pull request merged**
