### PR TITLE
Beta 6 fixes/improvements (2nd)

### PR DESCRIPTION
**Pull request by obuchtala**
- fixed bug in BrowserDOMElement 
- improved IsolatedNode step-into behavior
  -> now uses TAB and tries to find first surface if no grabFocus() available

### CODE REVIEW

**Comment by obuchtala** [comment]
@andene can you try this out?

**Comment by khlbrg** [comment]
Yeah, it works with tab 👍

**Comment by khlbrg** [comment]
ping @oliver----

**Comment by obuchtala** [comment]
@andene ok. As soon everything is green I will merge this into master and publish as v1.0.0-beta.6.3

**Comment by michael** [comment]
There is some stuff in surface-fixes, which may also go into beta.6.3. Can you check Oliver?

**Comment by obuchtala** [comment]
Will do

**Pull request merged**
