### PR TITLE
Some UI docs

### PR DESCRIPTION
**Pull request by Integral**

### CODE REVIEW

**Comment by michael** [comment]
A bunch of things have changed so I will need to rebase your docs when done. Hope I finish my refactorings over the weekend and we can get Substance Beta 3 out at the beginning of next week.

**Comment by Integral** [comment]
Note that I did sync with master.

**Comment by michael** [comment]
Talking about these changes here: https://github.com/substance/substance/pull/334

**Comment by Integral** [comment]
I'm not sure what could intersect here, so do what you want.
What I really did not like that part of commits came from master or other branches, so it's not really possible to work only with api-docs branch.

**Comment by michael** [comment]
Hey I've synced latest stuff with master. Can you clean this up a bit.. like just squashing the commits? I will merge it into master then. Thanks a lot!

**Comment by Integral** [comment]
mmm... it's hard to rebase, I did merge in the middle of the process...

**Comment by michael** [comment]
It's rebased now. Please review and push merge button :)

**Comment by michael** [comment]
Oh oh.. broken tests. Don't merge!

**Comment by michael** [comment]
Now looks good. Gosh.. rebasing... but more and more I'm understanding it. Needs practice. Please check and merge.

**Comment by Integral** [comment]
@michael what changed in commit history?

**Comment by michael** [comment]
I left commits the same - just edited some using the rebase workflow. It's similar to resolving merge conflicts.

**Comment by Integral** [comment]
Should we sync api-docs again?

**Comment by michael** [comment]
sync api docs?

**Comment by Integral** [comment]
yes, this branch or maybe it's better to create a new one...

**Comment by michael** [comment]
ah for more docs... create new one yes.

**Pull request merged**
