### PR TITLE
Restructurings.

### PR DESCRIPTION
**Pull request by obuchtala**
We changed layout of modules and naming of source files. Plus other minor cleanup.

### CODE REVIEW

**Comment by obuchtala** [comment]
@michael unfortunately, this branch is based on an older commit part of the embeds branch which has been merged already.
Could you rebase this branch, resolving conflicts?

**Comment by michael** [comment]
Yeah those were the hotfixes we did on Wednesday. 

https://github.com/substance/substance/commit/cd1e482a8f6fbbeb38873d7569b5dd71734a972f
https://github.com/substance/substance/commit/3f82a86a63129d8344484492bf3ac1ca26f09f91

Will rebase.

**Comment by michael** [comment]
Is now rebased. Can you make your changes in a separate branch and we work with pull requests into ui-reorganization?

Will now complete the transition for the UI module, then take care of util and for the rest of the day focus on applying the CSS rules.

**Comment by obuchtala** [comment]
> Is now rebased. Can you make your changes in a separate branch and we work with pull requests into ui-reorganization?

We can do that.

**Comment by obuchtala** [comment]
@michael my work is done.
Plz, have a look and merge this PR if fine.

**Comment by obuchtala** [comment]
wait... one more renaming: transformation -> transform

**Comment by obuchtala** [comment]
@michael now

**Pull request merged**
