### PR TITLE
Append and remove child API for inline nodes.

### PR DESCRIPTION
**Pull request by Integral**
@oliver---- this is all I need regarding XML inline nodes API.
However there are couple of methods left in XMLElementNode.js which I didn't copied. It maybe a good idea to move them as well for XML API compatibility. What do you think?

### CODE REVIEW

**Comment by obuchtala** [comment]
We probably would want to share the implementation by using a set of functions, e.g. `appendChild(xmlNode, newChild)`. Then we can avoid code duplication.

**Comment by obuchtala** [comment]
Would you like to do that? :)

**Comment by Integral** [comment]
Sure!

**Comment by Integral** [comment]
I think you can merge!

**Comment by obuchtala** [comment]
Could you extract the duplicate implementations into a shared file, say `xml/xmlNodeHelpers.js` and use it from `XMLElementNode` and `XMLInlineElementNode`?

Every such shared function would take the `node` as first argument.
For example:
```
appendChild(xmlNode, child) {
  insertAt(xmlNode, xmlNode._childNodes.length, child)
}
```
This way we avoid code duplication.

**Comment by Integral** [comment]
Done!

**Comment by obuchtala** [comment]
Thx!

**Comment by obuchtala** [comment]
Published.

**Pull request merged**
