### PR TITLE
Fixing the Clipboard.

### PR DESCRIPTION
**Pull request by obuchtala**

### CODE REVIEW

**Comment by obuchtala** [comment]
I need to try out more... and see if we can tighten things with tests.

**Comment by michael** [comment]
Did you check if this works: https://github.com/substance/substance/issues/176

**Comment by obuchtala** [comment]
Nope. thx. will check.

**Comment by obuchtala** [comment]
This works now. Still there might be issues. In Beta 3 we should work on building tests for the Clipboard.
Also we need a concept for better handling id collisions when pasting from external, which mainly happens when you copy'n'paste from the same doc in another tab.

**Comment by obuchtala** [comment]
@michael if you want to try out... now is the time

Before merging I want to cleanup the commits.

**Comment by michael** [comment]
Will do. In meanwhile.. Can you review: https://github.com/substance/substance/pull/264

**Comment by michael** [comment]
I pasted a huge chunk from a selection on a github issue page. Got this:

image

**Comment by obuchtala** [comment]
Obviously, the clipboard content is just fragments... need to fix.

**Comment by michael** [comment]
Need to move location again. Currently working from kalemegdan park and fingers are getting cold.

photo on 20-11-15 at 15 55

**Comment by obuchtala** [comment]
Crazy! Michael the drifter ;)

**Comment by obuchtala** [comment]
Working on a better integration of Clipboard into our Components world plus adding tests.

**Comment by obuchtala** [comment]
@michael got rid of phantomjs... though, lost coverage reports... will work on that in beta 3.

**Comment by obuchtala** [comment]
My studies on Clipboard content: https://gist.github.com/oliver----/232f6e0b17a0af067d1b

**Comment by obuchtala** [comment]
Done!

**Pull request merged**
