### PR TITLE
Introduce Configurator API

### PR DESCRIPTION
**Pull request by michael**
Implements a plugin architecture for ProseEditor.

### CODE REVIEW

**Comment by michael** [comment]
Please review and if green light I will merge into devel. I also updated the examples and they are mostly working. I deleted all note/notepad stuff though, as we want to have smaller examples anyways.

**Comment by michael** [comment]
Please also review: https://github.com/substance/examples/pull/13/files

**Comment by obuchtala** [comment]
:+1: Looking good :)

Let's merge and use beta5 to fine tune things.

**Comment by michael** [comment]
Alright! :)

**Pull request merged**
