### PR TITLE
Numerical addressing 

### PR DESCRIPTION
**Pull request by obuchtala**
Moving towards a next generation internal addressing scheme which will hopefully help us getting rid of the ugly and error prone container + container annotation index implementation.

### CODE REVIEW

**Comment by obuchtala** [comment]
@michael could you give me your feedback on the new address based API?
Some examples:
- Getting an address for a path:
  https://github.com/substance/substance/blob/b11916f50a0d0e3b1e90accea1654ad197335c5c/test/unit/document/container.test.js#L12
- Traversing addresses:
  https://github.com/substance/substance/blob/b11916f50a0d0e3b1e90accea1654ad197335c5c/test/unit/document/container.test.js#L49
  https://github.com/substance/substance/blob/b11916f50a0d0e3b1e90accea1654ad197335c5c/test/unit/document/container.test.js#L119
- Getting a range of paths:
  https://github.com/substance/substance/blob/b11916f50a0d0e3b1e90accea1654ad197335c5c/test/unit/document/container.test.js#L194
- Comparing addresses:
  https://github.com/substance/substance/blob/b11916f50a0d0e3b1e90accea1654ad197335c5c/document/container_selection.js#L234
  https://github.com/substance/substance/blob/b11916f50a0d0e3b1e90accea1654ad197335c5c/document/container_selection.js#L243

Some places where this is used already:
https://github.com/substance/substance/blob/b11916f50a0d0e3b1e90accea1654ad197335c5c/document/transformations/copy_selection.js#L77

The good thing about addresses is:
- they are sortable/comparable
- address is an array of indexes which represent childIndexes

From an address you can get to the top-level node using:

```
container.getChildAt(address[0]);
```

The last segment of an address is always the property index. E.g. in paragraphs there is only one property, so this is always 0. In a structured node, such as a figure, there are multiple properties. The propertyName can be revealed using:

```
node.getComponents()[_.last(address)]
```

**Comment by michael** [comment]
Thanks, I will have a look later! Need to go now.

**Comment by michael** [comment]
This is good stuff! I think it's a powerful concept to allow hierarchical addressing (for lists etc.) while still allowing a flat view of components. I read through the tests, and I have not much to add. I'd like to test this inside the writer app, but there are still too many things breaking.

**Comment by obuchtala** [comment]
Hmmm. Maybe I was too fast with removing the container annotation index regarding smooth transition.
Should I recover that, so that we can try this out iteratively in the writer?

**Comment by michael** [comment]
Not sure, probably it's more efficient to keep it a radical change. :) But maybe we should bring it together when I'm back. Also I think this should be tested first with the editor interface, then moving on to the writer. I'd rather continue with my Writer Refactor efforts, while it's getting better, there are still some smelly things I'd like to get rid of.

Maybe you have time to give me some thoughts regarding #63.

**Comment by obuchtala** [comment]
@michael plz review and merge

**Comment by michael** [comment]
Looks very good. I didn't see anything break in the Lens Writer integration. Merging.

**Pull request merged**
