### PR TITLE
File uploading

### PR DESCRIPTION
**Pull request by Integral**
It should work. At least in modern browsers.
Note that there is something wrong with saving of figures. It's not saving and not broadcasting, but without errors.
Hubclient will emit uploading progress percents.

### CODE REVIEW

**Comment by michael** [comment]
> Note that there is something wrong with saving of figures. It's not saving and not broadcasting, but without errors.

Don't understand. First you say it works, then it doesn't work ;) What means broadcasting? Sorry, perfect confusion ;)

**Comment by Integral** [comment]
Uploading is works and you will see the image. But other collaborators will not see it as well as you after refreshing the page.

**Comment by michael** [comment]
Ah ok. But that's on my end then.

**Comment by michael** [comment]
Tested and works. For progress I will do a separate iteration, but does not have priority yet.

**Pull request merged**
