### PR TITLE
Coverage Reports

### PR DESCRIPTION
**Pull request by obuchtala**
- re-activated istanbul to create coverage reports
- after successful builds on travis they are pushed to coveralls: https://coveralls.io/github/substance/substance

### CODE REVIEW

**Comment by Integral** [comment]
There is also coverify... Did you try it?

**Comment by obuchtala** [comment]
Not worth to look at. Why the hassle. Istanbul is way more mature.

**Comment by obuchtala** [comment]
BTW, `coverify` is basically a browserify transform plus a cli to create a report.
Istanbul plays well together with karma -- out-of-the-box. Being well documented and actively developed.

**Comment by Integral** [comment]
Kk

**Pull request merged**
