### PR TITLE
Html props

### PR DESCRIPTION
**Pull request by obuchtala**
Implements #41

### CODE REVIEW

**Comment by michael** [comment]
Nice for comp.text(). I have to admit I've been always confused about props vs attrs in jQuery. I just wonder what are situations where attr does not suffice for setting things?

``` js
QUnit.test("Accessing a HTML property via comp.htmlProp()", function(assert) {
  var comp = $$('input').htmlProp('type', 'text')._render();
  assert.equal(comp.htmlProp('type'), 'text', 'Input field should be of type "text".');
});
```

This would work fine with with attr too?

I wonder if we should only implement a read only htmlProp() version for accessing things like `nodeType` which don't have an attribute correspondence.

Generally speaking, for our $$ constructor we either construct a user component by passing props (some app data) or we construct an html element, where we pass html attributes, and css classes etc. just enough to construct an html element in the end. I'm not sure if it needs the difference between attrs and props (for settings things i mean).

I'm just thinking how we can avoid confusion between user component props, html attributes and html props.

If I'm calling attr('data-id', 'foo') on a user component, this attr data gets stored on the element right? not on the component (props).

**Comment by obuchtala** [comment]
The concern about confusion was the centre of my question in #41.

Actually, input.value is one example of a property. $.attr('value', val) sets the default value, but on the other side $.attr('value') does not provide the correct value after being updated by user. Looking at the native DOM element the difference is, that $.attr() changes el.attributes, while $.prop() the property of el.

So there are actually 2 different concepts, while as I said, props are way less often used than attributes, because most often we are using spans and divs which don't have any props we need.

**Comment by obuchtala** [comment]
You're right about input.type, it can be set using $.attr().

**Comment by obuchtala** [comment]
See http://api.jquery.com/prop/, there is an explanation of the difference between attr and prop.

**Comment by michael** [comment]
We should have some dedicated naming discussion I think.. and when we want to be jQuery compatible with our API. It's good to have support for props. Let's merge this and discuss later how we can reduce confusion. The props vs attrs dilemma is definitely not our fault. ;)

**Pull request merged**
