### PR TITLE
OO.extend() refactor

### PR DESCRIPTION
**Pull request by obuchtala**
Improved to make it easier to customize the extend implementation.
Plus: now OO.extend() allows for mixins.

### CODE REVIEW

**Comment by michael** [comment]
So init goes away in favor of didInitialize?

**Comment by obuchtala** [comment]
No built-in initializer anymore. didInitialize is not built-in but rather called by Component and now also by Node.

**Comment by michael** [comment]
Ah, yeh that's good I think!

**Comment by michael** [comment]
Can you quickly explain:

``` js
var extend = function(parent, keyProps, afterHook, proto) {};
```
- parent is clear.
- keyProps are value properties (no functions?)
- afterHook?
- proto only used for mixin or do I generally have to pass prototype functions there?

**Comment by obuchtala** [comment]
keyProps: Some of the props in the proto object may be keywords, i.e., they may be treated in a different way, such as name goes to constructor.static.name.
afterHook: look at the data node implementation.
proto: as you would expect, plain object, or now also a sequence of plain objects

**Comment by obuchtala** [comment]
Note: you never call this function. You call Node.extend which has everything bound already, and only expects the proto.

**Comment by michael** [comment]
Yeah I'm trying to finally understand this makeExtendFunction thing.

OK so when I now do Foo.extend I can use it like this:

``` js
Foo.extend({
  properties: {
    name: "Foo",
    type: "bar"
  },
  myFunc: function() {}
});
```

where `properties` is now treated specially to store properties on the class, which would be equivalent to:

``` js
Foo.static.name = 'Foo';
```

?

Thanks!

**Comment by obuchtala** [comment]
Not in general, but if Foo is extending Node, then the Node afterHook will put the properties (~schema) into Foo.static.schema. It also puts 'name' into Foo.static.name. This is defined by Data.Node when calling OO.makeExtensible.

**Comment by obuchtala** [comment]
Please look at a Node class... you see properties, name and also displayName in use.

**Comment by michael** [comment]
Ah and they go to the schema then.

https://github.com/substance/substance/blob/oo-extend-refactor/data/node.js#L194-L196

And when I would not use the extend pattern for nodes I would specify this.properties on the Foo.Prototype... like you did in Container.

Good stuff. Hit the merge! :)

**Comment by obuchtala** [comment]
Exactly.

Formerly I had this in a static property, but this was inconsistent with the defineProperties magic. So I dropped that, and moved to defining it on the proto.

**Pull request merged**
