### PR TITLE
Correct filename case

### PR DESCRIPTION
**Pull request by asmecher**
Looks to me like there's an upper/lowercase mismatch between TOCPanel and TocPanel. This PR renames the file (not sure whether you'd prefer that or renaming references to it).

### CODE REVIEW

**Comment by obuchtala** [comment]
Thx. That is exactly how we want to do it.
I will merge this after making sure that we require it correctly in other places.

**Comment by michael** [comment]
Fixed this for Lens. Merging. Thanks @asmecher.

**Comment by asmecher** [comment]
Good sharing a bottle of wine with you!

**Comment by obuchtala** [comment]
Yes indeed! That was nice :)

**Pull request merged**
