### PR TITLE
Streamline configurator API's.

### PR DESCRIPTION
**Pull request by michael**
Move ProseEditor-specific API into separate ProseEditorConfigurator. Do not import firstPackage on construction. This is too early as inherited configurators may to things on construction before the first package is imported.

### CODE REVIEW

**Comment by michael** [comment]
Please review. I removed firstPackage argument from the constructor, so this change will break the examples. If you are good with this I will update the examples and then merge.

**Comment by obuchtala** [comment]
👍

**Comment by Integral** [comment]
Could you please explain new concept?

**Comment by michael** [comment]
@Integral There is no new concept. It's just a realization that we should use multiple configurators to configure Reader/Writer separately. I need to get the examples updated and the PR's merged. I will be in the chat once done, so we can discuss the Notes app short.

**Pull request merged**
