### PR TITLE
[Work in progress] List editing behavior

### PR DESCRIPTION
**Pull request by sunu**
Hi,
I'm working on list editing behavior. Very basic implementations for now, but I would love some feedback.
Thanks.

### CODE REVIEW

**Comment by obuchtala** [comment]
Great!
I will take a look and give you feedback...

**Comment by obuchtala** [comment]
@sunu thanks for starting this.
I have set up a branch https://github.com/substance/substance/tree/list-editing which is based on top of latest master, where I have added some preparations to register editing behaviors.
I will add a simple integration to https://github.com/substance/examples.

First it would be good if you could rebase your changes onto substance/substance@list-editing.

**Comment by sunu** [comment]
@oliver---- Hi, I've rebased the changes onto the list-editing branch.

**Comment by sunu** [comment]
@oliver---- I was also wondering if there is any alternative communication channel for the project other than Github issues where I could ask some quick questions.

**Comment by obuchtala** [comment]
Hey,
Thx for rebasing. Communication wise, the best is email: oliver at substance.io
If we need to chat, we can use https://gitter.im/substance/substance
I will take another look at your implementation today, making a plan for next steps.
Cheers, Oliver

**Comment by sunu** [comment]
Great! I asked my question in the Gitter channel.

**Comment by michael** [comment]
Hey sorry we never picked this up. We have a very limited list implementation for beta 4 now but we want to get solid list support into beta 5 and would be glad to have your help. Before we start I want to evaluate wether we want the list to be implemented as an isolated node or not. Doing it as an isolated node would simplify the implementation and lets us treat lists more semantically. However, we editing behavior will differ from what people are used in MS word etc. We must should discuss if we want to allow complex content (another container) in a list item.

**Comment by sunu** [comment]
Hey @michael 
I closed the PR since my branch has significantly diverged from upstream Substance master. But yes, I would love to help implement more complete list editing support into Substance once you have a plan in place.

**Pull request closed without merging**
