### PR TITLE
More fixes for IsolatedNodes.

### PR DESCRIPTION
**Pull request by obuchtala**

### CODE REVIEW

**Comment by michael** [comment]
Nice!

I switched to a dedicated UnsupportedInlineNode implementation for scientist and made the XML editable. Just somehow managed to brake the inline-wrapper stuff, so figures are gona. Maybe you can have a look or we check it together.

**Comment by michael** [comment]
Moving crossref editing into a modal as well, just less noise during the editing.

**Comment by obuchtala** [comment]
Cool

**Comment by obuchtala** [comment]
The UnsupportedIN work is on scientist?

**Comment by michael** [comment]
yep. structured branch.

**Pull request merged**
