### PR TITLE
New tools/commands for lists

### PR DESCRIPTION
**Pull request by podviaznikov**
Up for initial review: Command and tool to create two types of lists.

### CODE REVIEW

**Comment by michael** [comment]
Thank you! :)

You could pass an ordered property like so:

```js
config.addCommand('insert-unordered-list', InsertListCommand, { nodeType: 'list', ordered: false })
```

In the command implementation you can access it via `this.config.ordered`. Also see `ui/Command.js` for API.

**Comment by podviaznikov** [comment]
@michael perfect! That what I was missing. Will update PR and have one command

**Comment by podviaznikov** [comment]
Updated package. Not 100% sure with German labels. I've used Google Translate but not very confident with the results.

Also not sure how to test it? How do you test packages? Should I add PR into examples repo?

**Comment by michael** [comment]
'unordered list' is 'Aufzählung', 'ordered list' is 'Nummerierte Liste'. Could you rebase your branch to develop? Then we have a cleaner merge. Thank you!

**Comment by podviaznikov** [comment]
Updated, added few fixes too

**Comment by michael** [comment]
Ready to merge. Only two requests:

- Rewrite commit history so no merge commits are visible (git rebase -i)
- Commit messages should start with upper case letter and end with ".". E.g. "Add label translations."

Thank you!

**Comment by podviaznikov** [comment]
@michael done. Let me know if there are some other problems

**Comment by michael** [comment]
Looking all good! Thank you!

**Pull request merged**
